backend:
  name: github
  repo: visualmulia/sudutkreatif-blog
  branch: main
  base_url: https://sudutkreatif.web.id # Your custom domain to avoid cross-domain browser blocks
  auth_endpoint: api/auth # Redirects to our Vercel Serverless Function

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["Workspace", "Setup"] }
      - { label: "Body", name: "body", widget: "markdown" }
